import { CloseInjuryUseCase } from '@/aplication/use-cases/availability/CloseInjuryUseCase';
import { CreateInjuryUseCase } from '@/aplication/use-cases/availability/CreateInjuryUseCase';
import { CreateAttachmentSignedUrlUseCase } from '@/aplication/use-cases/availability/CreateAttachmentSignedUrlUseCase';
import { CreateLinkAttachmentUseCase } from '@/aplication/use-cases/availability/CreateLinkAttachmentUseCase';
import { DeleteUnavailabilityAttachmentUseCase } from '@/aplication/use-cases/availability/DeleteUnavailabilityAttachmentUseCase';
import { GetCategoriesForAvailabilityUseCase } from '@/aplication/use-cases/availability/GetCategoriesForAvailabilityUseCase';
import { GetMedicalDetailsUseCase } from '@/aplication/use-cases/availability/GetMedicalDetailsUseCase';
import { GetPlayerAvailabilityUseCase } from '@/aplication/use-cases/availability/GetPlayerAvailabilityUseCase';
import { GetPlayerForAvailabilityUseCase } from '@/aplication/use-cases/availability/GetPlayerForAvailabilityUseCase';
import { GetPlayersForAvailabilityUseCase } from '@/aplication/use-cases/availability/GetPlayersForAvailabilityUseCase';
import { GetPlayerUnavailabilitiesUseCase } from '@/aplication/use-cases/availability/GetPlayerUnavailabilitiesUseCase';
import { GetStaffDetailsUseCase } from '@/aplication/use-cases/availability/GetStaffDetailsUseCase';
import { GetUnavailabilityAttachmentsUseCase } from '@/aplication/use-cases/availability/GetUnavailabilityAttachmentsUseCase';
import { GetUnavailabilityByIdUseCase } from '@/aplication/use-cases/availability/GetUnavailabilityByIdUseCase';
import { GetUnavailabilityHistoryUseCase } from '@/aplication/use-cases/availability/GetUnavailabilityHistoryUseCase';
import { UploadFileAttachmentUseCase } from '@/aplication/use-cases/availability/UploadFileAttachmentUseCase';
import { UpdatePlayerInjuryFullUseCase } from '@/aplication/use-cases/availability/UpdatePlayerInjuryFullUseCase';
import { AvailabilityRepositoryImpl } from '@/data/repositories/availability/AvailabilityRepositoryImpl';

const availabilityRepository = new AvailabilityRepositoryImpl();

export const getCategoriesForAvailabilityUseCase = new GetCategoriesForAvailabilityUseCase(availabilityRepository);
export const getPlayerForAvailabilityUseCase = new GetPlayerForAvailabilityUseCase(availabilityRepository);
export const getPlayersForAvailabilityUseCase = new GetPlayersForAvailabilityUseCase(availabilityRepository);
export const getPlayerAvailabilityUseCase = new GetPlayerAvailabilityUseCase(availabilityRepository);
export const getPlayerUnavailabilitiesUseCase = new GetPlayerUnavailabilitiesUseCase(availabilityRepository);
export const getUnavailabilityByIdUseCase = new GetUnavailabilityByIdUseCase(availabilityRepository);
export const getStaffDetailsUseCase = new GetStaffDetailsUseCase(availabilityRepository);
export const getMedicalDetailsUseCase = new GetMedicalDetailsUseCase(availabilityRepository);
export const getUnavailabilityAttachmentsUseCase = new GetUnavailabilityAttachmentsUseCase(availabilityRepository);
export const getUnavailabilityHistoryUseCase = new GetUnavailabilityHistoryUseCase(availabilityRepository);
export const createInjuryUseCase = new CreateInjuryUseCase(availabilityRepository);
export const updatePlayerInjuryFullUseCase = new UpdatePlayerInjuryFullUseCase(availabilityRepository);
export const closeInjuryUseCase = new CloseInjuryUseCase(availabilityRepository);
export const createLinkAttachmentUseCase = new CreateLinkAttachmentUseCase(availabilityRepository);
export const uploadFileAttachmentUseCase = new UploadFileAttachmentUseCase(availabilityRepository);
export const deleteUnavailabilityAttachmentUseCase = new DeleteUnavailabilityAttachmentUseCase(availabilityRepository);
export const createAttachmentSignedUrlUseCase = new CreateAttachmentSignedUrlUseCase(availabilityRepository);
